version: '3.8'

services:
  color-changer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: color-changer-app
    ports:
      - "8000:8000"
    volumes:
      - ./color-changer-app:/app
    restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"     # Jenkins web interface
      - "50000:50000"   # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home: